#! /bin/sh 
#
#autogen -- run configuration things in the right order
#Developers only need to run this script once after fresh CVS
#checkout.  They may need it again after some changes in configure.in
#such as creation of new files from configure.

# $Id$
# Author: Paul_Kunz@slac.stanford.edu

libtoolize --force --automake
aclocal -I config/m4
autoconf
autoheader
automake --add-missing



